defaults:
  - system: hexa
  - reverse_kl
  - _self_

main_temp: 300.0

training:
  lr: 1.e-4
  batch_size: 1024

evaluation:
  big_eval_samples: 10_000_000

checkpointing:
  write_checkpoint_every: 50_000