defaults:
  - system: aldp
  - reverse_kl
  - _self_

main_temp: 1200.0

training:
  max_iter: 100_000

  lr: 1.e-4
  batch_size: 256

  training_mode:
    remove_top_k_energies: 10

checkpointing:
  write_checkpoint_every: 50_000