defaults:
  - fab
  - system: gmm
  - _self_

main_temp: 1.0

training:
  lr: 1.e-5
  batch_size: 8192

  max_iter: 50_000

  training_mode:
    mode_name: "fab"

    n_int_dist: 1 # (Changed from 8)
    n_outer: 1
    n_inner: 1 # (Changed from 4)
    epsilon: 0.05
    common_epsilon_init_weight: 0.05
    adjust_step_size_training: True
    alpha: 2.0

    # Trafo applied on the ICs before performing AIS
    # Syntax: {channel_name: (perform unbound atanh trafo?, scaler)}
    AIS_trafo_config:
      "TARGET": [True, 0.2]

    reject_spline_OOB_samples: False

    additional_sampling_eval:
      eval_p2q: False

    replay_buffer:
      n_updates: 8
      min_length: 64
      max_length: 512
      max_adjust_w_clip: 10

  max_grad_norm: 1000.0
  warmup_iters: 1000

  weight_decay: 1.e-5

evaluation:
  eval_every: 5_000
  big_eval_every: ${training.max_iter}
  NLL_every: 2_000

checkpointing:
  write_checkpoint_every: 10_000