# Syntax: ["What to transform", "What to condition on", Also add the reverse?, temperature-aware?]
# Next to the names of the channels, also "ALL" and "REMAINING" are supported.
# Channels can be combined using "+", e.g. "TORSIONS+ANGLES"

- ["TORSIONS", "TORSIONS", True, False]
- ["TORSIONS", "TORSIONS", True, False]
- ["TORSIONS", "TORSIONS", True, False]
- ["ANGLES", "TORSIONS", False, False]
- ["ANGLES", "ANGLES", True, False]
- ["ANGLES", "TORSIONS", False, False]
- ["ANGLES", "ANGLES", True, False]
- ["BONDS", "REMAINING", False, False]
- ["BONDS", "BONDS", True, False]
- ["BONDS", "REMAINING", False, False]
- ["BONDS", "BONDS", True, False]