# Syntax: ["What to transform", "What to condition on", Also add the reverse?, temperature-aware?]
# Next to the names of the channels, also "ALL" and "REMAINING" are supported.
# Channels can be combined using "+", e.g. "TORSIONS+ANGLES"

- ["ALL", "ALL", True, False]
- ["ALL", "ALL", True, False]
- ["ALL", "ALL", True, False]
- ["ALL", "ALL", True, False]
- ["ALL", "ALL", True, False]
- ["ALL", "ALL", True, False]
- ["ALL", "ALL", True, False]
- ["ALL", "ALL", True, False]