defaults:
  - default_system
  - energy_reg
  - _self_

name: "hexa"

val_data:
  "300.0": "./data/hexa/300K_test.npy"
  "1200.0": "./data/hexa/1200K_val.npy"
train_data:
  "300.0": "./data/hexa/300K_train.npy"

marginals_2D:
  "TORSIONS":
    - [0, 1]
    - [3, 4]
    - [6, 7]
    - [9, 10]
    - [12, 13]
marginals_2D_vmax: 12.5
tica_path_and_selection: null
tica_vmax: 14.0

default_checkpoint_paths: null