defaults:
  - default_system
  - energy_reg
  - _self_

name: "tetra"

val_data:
  "300.0": "./data/tetra/300K_test.npy"
  "1200.0": "./data/tetra/1200K_val.npy"
train_data:
  "300.0": "./data/tetra/300K_train.npy"

marginals_2D:
  "TORSIONS":
    - [0, 1]
    - [3, 4]
    - [6, 7]
marginals_2D_vmax: 12.0
tica_path_and_selection: null
tica_vmax: 14.0

default_checkpoint_paths: null